apiVersion: v1
kind: Service
metadata:
  name: order-app
  namespace: order
spec:
  type:  NodePort
  selector:
    app: order
    # 해당 셀렉터를 통해 트래픽을 받을 pod를 변경함
    version: "2.0"
  ports:
  - port:  80
    targetPort:  8080